# Generated by Django 6.0.7 on 2026-07-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='campus.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('conteudo', models.TextField()),
                ('data', models.DateField()),
                ('expira_em', models.DateField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='campus.campus')),
            ],
        ),
        migrations.CreateModel(
            name='UnitedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=20)),
                ('video', models.FileField(upload_to='united_news/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='united_news', to='campus.campus')),
            ],
        ),
    ]
