# Generated by Django 6.0.7 on 2026-08-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_alter_evento_options_evento_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitednews',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='united_news/capas/'),
        ),
    ]
