# Generated by Django 6.0.7 on 2026-09-02 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_campus_titulo_pastoral_horarioculto_nome_redesocial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('horario', models.TimeField()),
                ('observacao', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugroups', to='campus.campus')),
                ('lideres', models.ManyToManyField(blank=True, related_name='ugroups_liderados', to=settings.AUTH_USER_MODEL)),
                ('pastores', models.ManyToManyField(blank=True, related_name='ugroups_pastoreados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UGroupEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugroup_encontros_registrados', to=settings.AUTH_USER_MODEL)),
                ('ugroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encontros', to='ugroups.ugroup')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('ugroup', 'data')},
            },
        ),
        migrations.CreateModel(
            name='UGroupMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('entrou_em', models.DateField(auto_now_add=True)),
                ('ugroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='ugroups.ugroup')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugroups_participando', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ugroup', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='UGroupPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='ugroups.ugroupencontro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='ugroups.ugroupmembro')),
            ],
            options={
                'unique_together': {('encontro', 'membro')},
            },
        ),
    ]
