# Generated by Django 6.0.7 on 2026-09-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugroup',
            name='pastores',
        ),
        migrations.AddField(
            model_name='ugroup',
            name='pastor_apoio',
            field=models.CharField(blank=True, help_text='Texto livre, ex: "Prs. Jackson e Danúbia". Não vincula usuário nenhum.', max_length=150),
        ),
    ]
