# Generated by Django 6.0.7 on 2026-07-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('regiao', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('PT', 'Portugal')], max_length=2)),
                ('endereco', models.CharField(max_length=255)),
                ('cor_tema', models.CharField(max_length=7)),
                ('ano_fundacao', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='campus.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pastores/')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastores', to='campus.campus')),
            ],
        ),
    ]
