# Generated by Django 6.0.7 on 2026-08-18 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='titulo_pastoral',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Pastores', 'Pastores')], default='Pastor', max_length=10),
        ),
        migrations.AddField(
            model_name='horarioculto',
            name='nome',
            field=models.CharField(blank=True, help_text='Ex: "Culto de Oração", "Culto Midweek". Deixe em branco pra usar só o dia da semana.', max_length=100),
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('spotify', 'Spotify')], max_length=20)),
                ('url', models.URLField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='campus.campus')),
            ],
            options={
                'unique_together': {('campus', 'plataforma')},
            },
        ),
    ]
