# Generated by Django 6.0.7 on 2026-08-17 03:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('capa', models.ImageField(upload_to='series/capas/')),
                ('data_lancamento', models.DateField(help_text='Mês/data de referência da série')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='campus.campus')),
            ],
            options={
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('youtube_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('duracao_minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='series.serie')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('serie', 'numero')},
            },
        ),
    ]
