# Generated by Django 6.0.7 on 2026-08-20 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0002_campus_titulo_pastoral_horarioculto_nome_redesocial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('acesso_dashboard', models.BooleanField(default=False)),
                ('visao_geral_voluntarios', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='campus.campus')),
                ('lideres', models.ManyToManyField(blank=True, related_name='departamentos_liderados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campus', 'nome')},
            },
        ),
    ]
