# Generated by Django 6.0.7 on 2026-08-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='aprova_membros',
            field=models.BooleanField(default=False),
        ),
    ]
