# Generated by Django 6.0.7 on 2026-08-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_aprova_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='edita_membros',
            field=models.BooleanField(default=False),
        ),
    ]
