# Generated by Django 6.0.7 on 2026-08-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_edita_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='tipo',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10),
        ),
    ]
