# Generated by Django 6.0.7 on 2026-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0005_tornar_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='cria_conteudo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='edita_conteudo',
            field=models.BooleanField(default=False),
        ),
    ]
