# Generated by Django 6.0.7 on 2026-08-20 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(blank=True, choices=[('fundador', 'Fundador'), ('pastor_presidente', 'Pastor Presidente'), ('lider', 'Líder')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voluntarioperfil',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntarios', to='departamentos.departamento'),
        ),
    ]
