# Generated by Django 6.0.7 on 2026-08-20 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_campus_titulo_pastoral_horarioculto_nome_redesocial'),
        ('usuarios', '0002_usuario_nivel_acesso_voluntarioperfil_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_pendentes', to='campus.campus')),
                ('usuario_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastro_origem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
