# Generated by Django 6.0.7 on 2026-08-22 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_edita_membros'),
        ('usuarios', '0004_reestruturar_role_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('departamento_aprovado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departamentos.departamento')),
                ('departamento_fechado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='departamentos.departamento')),
                ('departamento_opcao_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='departamentos.departamento')),
                ('departamento_opcao_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='departamentos.departamento')),
                ('departamento_opcao_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='departamentos.departamento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas_voluntario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
