# Generated by Django 6.0.7 on 2026-08-22 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cadastrovoluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_dashboard', models.BooleanField(blank=True, null=True)),
                ('aprova_membros', models.BooleanField(blank=True, null=True)),
                ('edita_membros', models.BooleanField(blank=True, null=True)),
                ('visao_geral_voluntarios', models.BooleanField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissao_individual', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
