# Generated by Django 6.0.7 on 2026-08-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_permissaoindividual'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanelaCandidaturaVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cadastrovoluntario',
            name='aceitou_termo',
            field=models.BooleanField(default=False),
        ),
    ]
