# Generated by Django 6.0.7 on 2026-08-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_telefone_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissaoindividual',
            name='cria_conteudo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='permissaoindividual',
            name='edita_conteudo',
            field=models.BooleanField(null=True),
        ),
    ]
