# Generated by Django 6.0.7 on 2026-08-31 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_permissaoindividual_cria_conteudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoLeituraBiblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(default='nvi', max_length=10)),
                ('livro_slug', models.CharField(max_length=50)),
                ('capitulo', models.PositiveSmallIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posicao_leitura_biblia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
